import type { MetadataRoute } from 'next'
import { splitV2Enabled } from '@/lib/flags'

/**
 * The installed app is "Split". "Peanut Split" stays on the surfaces a search engine or a group
 * chat sees — the root `<title>`, `SITE_NAME`, the OG unfurls. A home screen has room for one word.
 *
 * Nothing per-room can appear here. The manifest is one static file fetched without credentials,
 * and a room slug IS the credential — so there is no shortcut to a room, and there never can be.
 */
export default function manifest(): MetadataRoute.Manifest {
    return {
        name: 'Split',
        short_name: 'Split',
        description: 'Split expenses with a link. No signup.',
        start_url: '/',
        scope: '/',
        display: 'standalone',
        display_override: ['standalone'],
        orientation: 'portrait',
        theme_color: '#FFC900',
        background_color: '#FAF4F0',
        /**
         * Long-press the launcher icon. English in every language, deliberately: the manifest is
         * fetched without credentials, so the `ps-locale` cookie cannot reach it, and `name` and
         * `description` above are English for the same reason.
         *
         * No icons — they are optional, every launcher falls back to the app icon, and three more
         * 96x96 assets are exactly the work that waits on `feat-logo`.
         */
        shortcuts: [
            // The one thing somebody opens the app cold to do, and the only screen that works with
            // no room on this device at all. `start_url` already covers "take me to my rooms".
            { name: 'New split', url: '/new' },
            // Only on a deployment that opted into v2 — /import calls notFound() otherwise, and a
            // launcher shortcut to a 404 is the definition of a dead end.
            ...(splitV2Enabled() ? [{ name: 'Import from Splitwise', url: '/import' }] : []),
        ],
        // Generated by scripts/generate-icons.mjs (`pnpm icons`) — don't hand-edit the PNGs.
        icons: [
            {
                src: '/icons/icon-192.png',
                sizes: '192x192',
                type: 'image/png',
                purpose: 'any',
            },
            {
                src: '/icons/icon-512.png',
                sizes: '512x512',
                type: 'image/png',
                purpose: 'any',
            },
            {
                src: '/icons/icon-192-maskable.png',
                sizes: '192x192',
                type: 'image/png',
                purpose: 'maskable',
            },
            {
                src: '/icons/icon-512-maskable.png',
                sizes: '512x512',
                type: 'image/png',
                purpose: 'maskable',
            },
        ],
    }
}
