import type { MetadataRoute } from 'next'

export default function manifest(): MetadataRoute.Manifest {
    return {
        name: 'Peanut Split',
        short_name: 'Split',
        description: 'Split expenses with a link. No signup.',
        start_url: '/',
        scope: '/',
        display: 'standalone',
        display_override: ['standalone'],
        orientation: 'portrait',
        // Pink, not Peanut's yellow: the two apps sit on the same home screen and the
        // installed shell should not read as the wrong one.
        theme_color: '#FF90E8',
        background_color: '#FAF4F0',
        // Generated by scripts/generate-icons.mjs (`pnpm icons`) — don't hand-edit the PNGs.
        icons: [
            {
                src: '/icons/icon-192.png',
                sizes: '192x192',
                type: 'image/png',
                purpose: 'any',
            },
            {
                src: '/icons/icon-512.png',
                sizes: '512x512',
                type: 'image/png',
                purpose: 'any',
            },
            {
                src: '/icons/icon-192-maskable.png',
                sizes: '192x192',
                type: 'image/png',
                purpose: 'maskable',
            },
            {
                src: '/icons/icon-512-maskable.png',
                sizes: '512x512',
                type: 'image/png',
                purpose: 'maskable',
            },
        ],
    }
}
