/* Split's doodles — hand-drawn line art, generated by design/doodles/build.py.
 *
 * DO NOT EDIT. Edit the clean geometry in design/doodles/parts/*.json and re-run
 *     python3 design/doodles/build.py --write
 *
 * Every path is stroke-only and sized to a 32-unit box, so a drawing takes the
 * ink of whatever it sits in (`stroke: currentColor` in <Doodle>) and needs no
 * second asset for a second background. See Doodle.tsx for the render side.
 */

export const DOODLE = {
    /* a drawn question mark in a ring — the affordance that opens an explainer */
    question:
        'M3.8 15.9C4.1 16.8 4.8 19.4 5.9 21C7 22.6 8.6 24.6 10.4 25.6C12.3 26.7 14.9 27.2 16.9 27.3C18.9 27.3 20.9 26.9 22.5 26C24.2 25.1 25.9 23.3 26.9 21.7C27.8 20 28.3 17.8 28.1 16.1C27.8 14.3 26.7 12.7 25.6 11.2C24.5 9.6 23.2 8 21.5 6.9C19.7 5.9 17.3 5.2 15.2 5.1C13.1 4.9 10.5 5.3 8.8 6C7 6.8 5.6 8.2 4.8 9.8C4 11.5 3.9 14.9 3.8 15.9C3.6 17 3.4 15.1 3.8 15.9Z M16.8 24.2C16.8 24.3 16.9 24.3 17.1 24.4C17.2 24.5 17.3 24.7 17.4 24.8C17.6 24.9 17.8 25.1 18 25.2C18.1 25.3 18.2 25.4 18.3 25.3C18.4 25.3 18.5 25.2 18.6 25.1C18.7 24.9 18.7 24.8 18.8 24.6C18.8 24.5 19 24.1 18.9 24.1C18.9 24 18.5 24.1 18.3 24.1C18.1 24.1 17.9 24 17.7 24C17.5 24 17.3 24 17.1 23.9C17 23.9 16.8 23.7 16.7 23.7C16.7 23.8 16.8 24.1 16.8 24.2C16.8 24.3 16.7 24.2 16.8 24.2Z M10.6 12.1C10.6 11.8 10.5 10.8 10.6 10.2C10.7 9.7 10.9 9.2 11.2 8.8C11.6 8.4 12.1 8 12.6 7.8C13.1 7.6 13.6 7.5 14.2 7.4C14.7 7.3 15.4 7.3 16.1 7.4C16.8 7.4 17.4 7.5 18.1 7.7C18.8 7.9 19.6 8 20.1 8.5C20.5 8.9 20.7 9.6 20.9 10.2C21.1 10.8 21.2 11.4 21.3 11.9C21.3 12.5 21.2 13.1 21.1 13.6C20.9 14 20.6 14.3 20.3 14.6C20 15 19.5 15.5 19.1 15.8C18.7 16.2 18.3 16.5 18 17C17.7 17.4 17.6 17.8 17.5 18.4C17.4 19 17.4 20.2 17.4 20.5',
} as const

export type DoodleName = keyof typeof DOODLE

export const DOODLE_NAMES = Object.keys(DOODLE) as DoodleName[]

export const isDoodleName = (name: string): name is DoodleName => name in DOODLE
