#!/usr/bin/env python3
"""Split's doodle set — clean geometry in, hand-drawn SVG paths out.

    python3 design/doodles/build.py                     # report: what is new or changed
    python3 design/doodles/build.py --write             # write the shipped TS module
    python3 design/doodles/build.py --png sheet.png     # contact sheet of every drawing
    python3 design/doodles/build.py --png a.png --only pizza,beer
    python3 design/doodles/build.py --manifest cast.js --only personaghost,personabear

Lifted whole from `munin/design/raven-doodles/build.py`, including `rough.py`
itself, so Split's line is the same line. Read that file's header for why the
roughening works the way it does; the short version is that the noise is one
smooth 2-D field per drawing rather than noise along each stroke, which is what
keeps coincident lines coincident and makes the result read as a drawing traced
onto crumpled paper instead of a tangle.

WHY A BUILD STEP. The app pays nothing at runtime — the shipped asset is already
drawn — and `rough.py` is seeded, so two builds of the same source are
byte-identical and a diff means somebody changed a drawing.

The clean geometry lives in `parts/*.json`, one file per batch, merged by name.
Splitting it that way is not organisation for its own sake: the set was drawn by
several people at once, and one file per batch is what let them work without
stepping on each other.

Each entry is `{"d": …, "dots": [[cx, cy, r], …], "note": …}` in a 32-unit box.

  d      the strokes, as SVG path data. Stroke only — `fill` is never set, so a
         shape that relies on being filled comes out as an outline of itself.
  dots   true circles, drawn as `<circle>` and roughened as circles. Anything
         round belongs here: run through the path resampler a circle comes out
         a wobbly polygon.
  note   one line, what it is meant to read as. Kept in the shipped file.
  name, vibe, bg, accent, ink
         optional design-review metadata. These never add runtime weight to the
         shipped module; the manifest and contact-sheet outputs use them to test
         colored backplates and labels around the same single-color path.

LEGIBILITY, the floor Munin found the hard way: these are stroked at ~1.6–2px in
a 32-unit box and shown as small as 20px. Below about r2.5 a loop fills in and
reads as a full stop, and more-and-finer always loses to fewer-and-longer. Three
long rays read as a sun; five short ones read as fuzz.
"""
import argparse
import glob
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
import rough  # noqa: E402

PARTS = os.path.join(HERE, "parts")
OUT = os.path.join(REPO, "apps", "web", "src", "components", "ui", "doodles.ts")

HEAD = """/* Split's doodles — hand-drawn line art, generated by design/doodles/build.py.
 *
 * DO NOT EDIT. Edit the clean geometry in design/doodles/parts/*.json and re-run
 *     python3 design/doodles/build.py --write
 *
 * Every path is stroke-only and sized to a 32-unit box, so a drawing takes the
 * ink of whatever it sits in (`stroke: currentColor` in <Doodle>) and needs no
 * second asset for a second background. See Doodle.tsx for the render side.
 */

export const DOODLE = {
"""

TAIL = """} as const

export type DoodleName = keyof typeof DOODLE

export const DOODLE_NAMES = Object.keys(DOODLE) as DoodleName[]

export const isDoodleName = (name: string): name is DoodleName => name in DOODLE
"""


def load():
    """Every batch, merged by name. A name in two batches is a bug, not a
    last-one-wins — the two drawings would silently take turns by filename."""
    merged, seen = {}, {}
    for path in sorted(glob.glob(os.path.join(PARTS, "*.json"))):
        batch = os.path.basename(path)
        with open(path, encoding="utf-8") as f:
            entries = json.load(f)
        for name, entry in entries.items():
            if name in seen:
                raise SystemExit("duplicate drawing %r in %s and %s" % (name, seen[name], batch))
            seen[name] = batch
            merged[name] = entry
    return dict(sorted(merged.items()))


def build(source):
    out = {}
    for name, entry in source.items():
        circles = "".join(
            '<circle cx="%s" cy="%s" r="%s"/>' % tuple(dot) for dot in entry.get("dots", ())
        )
        drawn = rough.redraw(circles + '<path d="%s"/>' % entry["d"], rough.DOODLE, 32)
        out[name] = " ".join(rough.re.findall(r'\bd="([^"]*)"', drawn))
    return out


def module(source, paths):
    lines = []
    for name, d in paths.items():
        note = source[name].get("note")
        if note:
            lines.append("    /* %s */\n" % note)
        lines.append("    %s: '%s',\n" % (name, d))
    return HEAD + "".join(lines) + TAIL


def sheet(source, paths):
    """A contact sheet at the two sizes that matter: large enough to judge the
    expression, and small enough to expose avatar-scale tangles."""
    cells = "".join(
        '<figure style="--bg:%s;--accent:%s;--ink:%s">'
        '<div class="art big"><i></i><svg viewBox="0 0 32 32"><path d="%s"/></svg></div>'
        '<div class="art small"><i></i><svg viewBox="0 0 32 32"><path d="%s"/></svg></div>'
        "<figcaption><strong>%s</strong><em>%s</em></figcaption></figure>"
        % (
            source[n].get("bg", "#fff"),
            source[n].get("accent", "#ffc900"),
            source[n].get("ink", "#202027"),
            d,
            d,
            source[n].get("name", n),
            source[n].get("vibe", source[n].get("note", "")),
        )
        for n, d in paths.items()
    )
    return (
        "<!doctype html><meta charset=utf-8><style>"
        "body{margin:0;background:#FAF4F0;color:#202027;"
        "font:11px ui-rounded,'Arial Rounded MT Bold',system-ui,sans-serif;display:flex;flex-wrap:wrap;gap:6px;padding:10px}"
        "figure{margin:0;width:132px;min-height:178px;background:#fff;border:1.5px solid #202027;"
        "border-radius:10px;padding:6px;display:grid;grid-template-columns:1fr 34px;"
        "grid-template-rows:112px auto;align-items:end;gap:4px}"
        ".art{position:relative;display:grid;place-items:center;overflow:hidden;border:1.5px solid #202027;"
        "border-radius:50%;background:var(--bg);color:var(--ink)}"
        ".art i{position:absolute;width:62%;height:38%;right:-8%;bottom:4%;border-radius:50%;"
        "background:var(--accent);transform:rotate(-14deg)}"
        "svg{position:relative;z-index:1;width:78%;height:78%;fill:none;stroke:currentColor;"
        "stroke-linecap:round;stroke-linejoin:round;overflow:visible}"
        ".big{width:112px;height:112px;stroke-width:1.55}"
        ".small{width:30px;height:30px;margin-bottom:6px;stroke-width:2}"
        "figcaption{text-align:left;line-height:1.25;grid-column:1/-1}"
        "figcaption strong{display:block;font-size:12px}"
        "em{display:block;margin-top:2px;font-style:normal;color:#5F646D}"
        "</style>" + cells
    )


def browser_manifest(source, paths):
    """Generate a data bridge for static design reviews from the shipped paths."""
    canaries = [
        {
            "key": name,
            "name": source[name].get("name", name),
            "vibe": source[name].get("vibe", ""),
            "bg": source[name].get("bg", "#fff"),
            "accent": source[name].get("accent", "#ffc900"),
            "ink": source[name].get("ink", "#202027"),
            "path": paths[name],
        }
        for name in paths
    ]
    return "window.PERSONA_CANARIES = %s;\n" % json.dumps(canaries, ensure_ascii=False)


CHROME = os.path.expanduser(
    "~/.cache/ms-playwright/chromium_headless_shell-1217/"
    "chrome-headless-shell-linux64/chrome-headless-shell"
)


def png(html, out, count):
    out = os.path.abspath(out)
    tmp = out + ".html"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(html)
    rows = (count + 5) // 6
    # Capped so the screenshot never breaks the 1000px house limit.
    subprocess.run(
        [CHROME, "--headless", "--disable-gpu", "--no-sandbox", "--hide-scrollbars",
         "--screenshot=" + out, "--window-size=980,%d" % min(1000, 28 + rows * 194),
         "file://" + tmp],
        check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )
    os.remove(tmp)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--png")
    ap.add_argument("--manifest", help="write browser-ready JS for a static design review")
    ap.add_argument("--only", help="comma-separated names, for the sheet")
    args = ap.parse_args()

    source = load()
    if args.only:
        wanted = [n.strip() for n in args.only.split(",") if n.strip()]
        missing = [n for n in wanted if n not in source]
        if missing:
            raise SystemExit("no such drawing: " + ", ".join(missing))
        source = {n: source[n] for n in wanted}
    paths = build(source)

    if args.png:
        png(sheet(source, paths), args.png, len(paths))
        print("sheet :", args.png, "(%d drawings)" % len(paths))

    if args.manifest:
        with open(args.manifest, "w", encoding="utf-8") as f:
            f.write(browser_manifest(source, paths))
        print("manifest :", args.manifest, "(%d drawings)" % len(paths))

    if args.write:
        with open(OUT, "w", encoding="utf-8") as f:
            f.write(module(source, paths))
        print("wrote :", OUT, "(%d drawings)" % len(paths))
    elif not args.png and not args.manifest:
        shipped = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        same = [n for n, d in paths.items() if "'%s'," % d in shipped]
        print("drawings:", len(paths), " already shipped byte-identical:", len(same))
        differ = [n for n in paths if n not in same]
        if differ:
            print("differ or new:", ", ".join(differ))
