#!/usr/bin/env python3
"""Split's doodle set — clean geometry in, hand-drawn SVG paths out.

    python3 design/doodles/build.py                     # report: what is new or changed
    python3 design/doodles/build.py --write             # write the shipped TS module
    python3 design/doodles/build.py --png sheet.png     # contact sheet of every drawing
    python3 design/doodles/build.py --png a.png --only pizza,beer

Lifted whole from `munin/design/raven-doodles/build.py`, including `rough.py`
itself, so Split's line is the same line. Read that file's header for why the
roughening works the way it does; the short version is that the noise is one
smooth 2-D field per drawing rather than noise along each stroke, which is what
keeps coincident lines coincident and makes the result read as a drawing traced
onto crumpled paper instead of a tangle.

WHY A BUILD STEP. The app pays nothing at runtime — the shipped asset is already
drawn — and `rough.py` is seeded, so two builds of the same source are
byte-identical and a diff means somebody changed a drawing.

The clean geometry lives in `parts/*.json`, one file per batch, merged by name.
Splitting it that way is not organisation for its own sake: the set was drawn by
several people at once, and one file per batch is what let them work without
stepping on each other.

Each entry is `{"d": …, "dots": [[cx, cy, r], …], "note": …}` in a 32-unit box.

  d      the strokes, as SVG path data. Stroke only — `fill` is never set, so a
         shape that relies on being filled comes out as an outline of itself.
  dots   true circles, drawn as `<circle>` and roughened as circles. Anything
         round belongs here: run through the path resampler a circle comes out
         a wobbly polygon.
  note   one line, what it is meant to read as. Kept in the shipped file.

LEGIBILITY, the floor Munin found the hard way: these are stroked at ~1.6–2px in
a 32-unit box and shown as small as 20px. Below about r2.5 a loop fills in and
reads as a full stop, and more-and-finer always loses to fewer-and-longer. Three
long rays read as a sun; five short ones read as fuzz.
"""
import argparse
import glob
import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
import rough  # noqa: E402

PARTS = os.path.join(HERE, "parts")
OUT = os.path.join(REPO, "apps", "web", "src", "components", "ui", "doodles.ts")

HEAD = """/* Split's doodles — hand-drawn line art, generated by design/doodles/build.py.
 *
 * DO NOT EDIT. Edit the clean geometry in design/doodles/parts/*.json and re-run
 *     python3 design/doodles/build.py --write
 *
 * Every path is stroke-only and sized to a 32-unit box, so a drawing takes the
 * ink of whatever it sits in (`stroke: currentColor` in <Doodle>) and needs no
 * second asset for a second background. See Doodle.tsx for the render side.
 */

export const DOODLE = {
"""

TAIL = """} as const

export type DoodleName = keyof typeof DOODLE

export const DOODLE_NAMES = Object.keys(DOODLE) as DoodleName[]

export const isDoodleName = (name: string): name is DoodleName => name in DOODLE
"""


def load():
    """Every batch, merged by name. A name in two batches is a bug, not a
    last-one-wins — the two drawings would silently take turns by filename."""
    merged, seen = {}, {}
    for path in sorted(glob.glob(os.path.join(PARTS, "*.json"))):
        batch = os.path.basename(path)
        with open(path, encoding="utf-8") as f:
            entries = json.load(f)
        for name, entry in entries.items():
            if name in seen:
                raise SystemExit("duplicate drawing %r in %s and %s" % (name, seen[name], batch))
            seen[name] = batch
            merged[name] = entry
    return dict(sorted(merged.items()))


def build(source):
    out = {}
    for name, entry in source.items():
        circles = "".join(
            '<circle cx="%s" cy="%s" r="%s"/>' % tuple(dot) for dot in entry.get("dots", ())
        )
        drawn = rough.redraw(circles + '<path d="%s"/>' % entry["d"], rough.DOODLE, 32)
        out[name] = " ".join(rough.re.findall(r'\bd="([^"]*)"', drawn))
    return out


def module(source, paths):
    lines = []
    for name, d in paths.items():
        note = source[name].get("note")
        if note:
            lines.append("    /* %s */\n" % note)
        lines.append("    %s: '%s',\n" % (name, d))
    return HEAD + "".join(lines) + TAIL


def sheet(source, paths):
    """A contact sheet at the two sizes that matter: 96px to see what you drew,
    and 24px to see whether it survives being small, which is the real test."""
    cells = "".join(
        '<figure><svg class=big viewBox="0 0 32 32"><path d="%s"/></svg>'
        '<svg class=small viewBox="0 0 32 32"><path d="%s"/></svg>'
        "<figcaption>%s<em>%s</em></figcaption></figure>"
        % (d, d, n, source[n].get("note", ""))
        for n, d in paths.items()
    )
    return (
        "<!doctype html><meta charset=utf-8><style>"
        "body{margin:0;background:#FAF4F0;color:#000;"
        "font:11px ui-monospace,monospace;display:flex;flex-wrap:wrap;gap:6px;padding:10px}"
        "figure{margin:0;width:132px;background:#fff;border:1px solid #000;padding:6px;"
        "display:flex;flex-direction:column;align-items:center;gap:2px}"
        "svg{fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;overflow:visible}"
        ".big{width:96px;height:96px;stroke-width:1.6}"
        ".small{width:24px;height:24px;stroke-width:1.9}"
        "figcaption{text-align:center;line-height:1.3}"
        "em{display:block;font-style:normal;color:#5F646D}"
        "</style>" + cells
    )


CHROME = os.path.expanduser(
    "~/.cache/ms-playwright/chromium_headless_shell-1217/"
    "chrome-headless-shell-linux64/chrome-headless-shell"
)


def png(html, out, count):
    tmp = out + ".html"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(html)
    rows = (count + 6) // 7
    # Capped so the screenshot never breaks the 1000px house limit.
    subprocess.run(
        [CHROME, "--headless", "--disable-gpu", "--no-sandbox", "--hide-scrollbars",
         "--screenshot=" + out, "--window-size=980,%d" % min(1000, 40 + rows * 176),
         "file://" + tmp],
        check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )
    os.remove(tmp)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--png")
    ap.add_argument("--only", help="comma-separated names, for the sheet")
    args = ap.parse_args()

    source = load()
    if args.only:
        wanted = [n.strip() for n in args.only.split(",") if n.strip()]
        missing = [n for n in wanted if n not in source]
        if missing:
            raise SystemExit("no such drawing: " + ", ".join(missing))
        source = {n: source[n] for n in wanted}
    paths = build(source)

    if args.png:
        png(sheet(source, paths), args.png, len(paths))
        print("sheet :", args.png, "(%d drawings)" % len(paths))

    if args.write:
        with open(OUT, "w", encoding="utf-8") as f:
            f.write(module(source, paths))
        print("wrote :", OUT, "(%d drawings)" % len(paths))
    elif not args.png:
        shipped = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        same = [n for n, d in paths.items() if "'%s'," % d in shipped]
        print("drawings:", len(paths), " already shipped byte-identical:", len(same))
        differ = [n for n in paths if n not in same]
        if differ:
            print("differ or new:", ", ".join(differ))
