/** Group names used only when a new room's name is left blank. */
export const ROOM_NAME_FALLBACKS = [
    'Cool kids room',
    'The Club',
    'Peanut Gallery',
    'The Nut House',
    'Shell Mates',
    'Mixed Nuts',
    'Salted Squad',
    'Nutty Buddies',
    'Goober Gang',
    'Legume League',
    'Nut Butter Crew',
    'The Peanut Pack',
    'The Crunch Crew',
    'The Snack Pack',
    'Chaos Coordinators',
    'Broke Besties',
    'Splurge Club',
    'Frugal Friends',
    'Big Spenders',
    'Penny Pinchers',
    'Adults Allegedly',
    'Impulse Buyers',
    'Team No Receipts',
    'The Bargain Bunch',
    'The Usual Suspects',
    'The Group Chat',
    'The Plus Ones',
    'The Lunch Bunch',
    'The Brunch Club',
    'The Dinner Club',
    'The Takeout Crew',
    'The Coffee Club',
    'The Afterparty Crew',
    'The Weekend Crew',
    'The Night Owls',
    'The Trip Committee',
    'The Detour Club',
    'The Side Quest Squad',
    'The Good Eggs',
    'The Odd Bunch',
    'The Cozy Crew',
    'The Couch Club',
    'The Tiny Committee',
    'The Butter Halves',
    'The Last-Minute Club',
    'The Tab Team',
    'The Split Squad',
    'The Chip-In Crew',
    'The Change Gang',
    'The Treat Committee',
] as const
